#!/bin/bash

# Exit if any command fails
set -e

# Variables
COMMIT=${1}
REMOTE=${2}
TIMESTAMP=`date`

# Directory we're in
echo "In directory `pwd`"
echo "Deploying commit: $COMMIT"

# Move to repo dir
cd repo

# Update our branches from origin
git fetch origin

# Checkout the branch that is going to be deployed
git checkout $COMMIT

# rsync to move to deploy directory
rm -rf ../deploy/wp-content

# Rsync over the repo
rsync -az --exclude .git --exclude .gitignore ./ ../deploy/wp-content/

# Copy the ENV file if it exists
cd ../
if [ -f .env.php ]; then
    cp .env.php deploy/wp-content/mu-plugins/app/
fi

# move to deploy folder
cd deploy/wp-content

cp ~/scripts/.gitignore-master .gitignore

# Build steps (composer, npm, gulp, etc)
composer install -o --prefer-dist --no-progress --no-dev

git add .
git commit -am "Build release $COMMIT [$TIMESTAMP]"

rsync -zhv -rlD "$(pwd -P)/" $2 --delete --exclude-from '/home/aaronholbrook/rsync-excludes.txt'
