#!/bin/bash

# Exit if any command fails
set -e

# Variables
COMMIT=${1}
REMOTE=${2}
TIMESTAMP=`date`

# Directory we're in
echo "In directory `pwd`"
echo "Deploying commit: $COMMIT"

# Move to repo dir
cd repo

# Update our branches from origin
git fetch origin

# Checkout the branch that is going to be deployed
git checkout $COMMIT

# rsync to move to deploy directory
rm -rf ../deploy/wp-content
rsync -avz --exclude .git --exclude .gitignore ./ ../deploy/wp-content/


cp ~/scripts/.gitignore-master .gitignore

# Build steps (composer, npm, gulp, etc)
composer install -o --prefer-dist --no-progress --no-dev -d wp-content

git add .
git commit -am "Build release $COMMIT [$TIMESTAMP]"

rsync -azhv "$(pwd -P)/" $2 --delete --exclude-from '~/scripts/rsync-excludes.txt'