#!/bin/bash

# Exit if any command fails
set -e

# Variables
COMMIT=${1:-master}
TIMESTAMP=`date`

# Directory we're in
echo "In directory `pwd`"
echo "Deploying commit: $COMMIT"

# Move to repo dir
cd repo

# Update our branches from origin
git fetch origin

# Checkout the branch that is going to be deployed
git checkout $COMMIT

# rsync to move to deploy directory
rm -rf ../deploy/wp-content
rsync -az --exclude .git --exclude .gitignore ./ ../deploy/wp-content/

# Copy the ENV file if it exists
cd ../
if [ -f .env.php ]; then
    cp .env.php deploy/wp-content/mu-plugins/app/
fi

# Move to deploy folder
cd deploy

cp ~/scripts/.gitignore-master .gitignore

cd wp-content/

# Build steps (composer, npm, gulp, etc)
composer install -o --prefer-dist --no-progress --no-dev

cd ../

git add .
git commit -am "Build release $COMMIT [$TIMESTAMP]"
git push -o nolint wpengine master
