#!/bin/bash

# Variables
COMMIT=${1:-master}
TIMESTAMP=`date`

# Directory we're in
echo "In directory `pwd`"
echo "Deploying commit: $COMMIT"

# Move to repo dir
cd repo

# Update our branches from origin
git fetch origin

# Checkout the branch that is going to be deployed
git checkout $COMMIT

# rsync to move to deploy directory
rm -rf ../deploy/wp-content
rsync -avz --exclude .git --exclude .gitignore ./ ../deploy/wp-content/

# Move to deploy folder
cd ../deploy

cp ~/.gitignore-master .gitignore

cd wp-content/

# Build steps (composer, npm, gulp, etc)
composer install -o --prefer-dist --no-progress --no-dev

# @todo place .env.php file from Deploybot

#git diff
#exit 1

git add .
git commit -am "Build release $COMMIT [$TIMESTAMP]"
git push wpengine master
