#!/bin/bash

# Exit if any command fails
set -e

# Variables
COMMIT=${1}
REMOTE=${2}
TIMESTAMP=`date`

echo '-----------------------------'
echo 'Welcome to Pusher, beginning build.'
echo '-----------------------------'

# Directory we're in
echo "In directory `pwd`"
echo "Deploying commit: $COMMIT"

# Move to repo dir
cd repo

# Update our branches from origin
git fetch origin

# Checkout the branch that is going to be deployed
git checkout $COMMIT

# rsync to move to deploy directory
rm -rf ../deploy/wp-content

# Rsync over the repo
rsync -az --exclude .git --exclude .gitignore ./ ../deploy/wp-content/

# Copy the ENV file if it exists
cd ../
if [ -f .env.php ]; then
    cp .env.php deploy/wp-content/mu-plugins/app/
fi

# Copy the auth.json file if it exists
if [ -f auth.json ]; then
    cp auth.json deploy/wp-content/auth.json
fi

# move to deploy folder
cd deploy/wp-content

cp ~/scripts/.gitignore-master .gitignore

# Combine excludes to allow custom exclusions
touch .excludes
cat ~/scripts/rsync-excludes.txt .excludes > rsync-excludes.txt

# Build steps (composer, npm, gulp, etc)
if [ -f composer.lock ]; then

    echo '-----------------------------'
    echo 'Running Composer'
    echo '-----------------------------'
    
    composer install -o --prefer-dist --no-progress --no-dev
fi

#git add .
#git commit -am "Build release $COMMIT [$TIMESTAMP]"

echo '-----------------------------'
echo "Beginning file transfer to server: $2 via rsync"
echo '-----------------------------'

rsync -zhrlD "$(pwd -P)/" $2 --delete --exclude-from 'rsync-excludes.txt'

echo '-----------------------------'
echo 'File transfer completed (see above for any issues)'
echo '-----------------------------'
